@echo off
setlocal
cd /d "%~dp0"
set "AIOSTREAMS_PREVIEW_TEST_UNAVAILABLE="
set "AIOSTREAMS_PREVIEW_TEST_VARIANT=fast-seek"
set "AIOSTREAMS_PREVIEW_USENET_BACKGROUND="
set "AIOSTREAMS_PREVIEW_HTTP_BACKGROUND="
set "AIOSTREAMS_PREVIEW_COST_LEARNING=off"
set "AIOSTREAMS_PREVIEW_GRID_REFERENCE=classic"
set "AIOSTREAMS_PREVIEW_USENET_MAX_DUTY="
set "AIOSTREAMS_PREVIEW_HTTP_MAX_DUTY="
start "" "%~dp0AIOStreams-Custom.exe"
